Repository Likelion-13th-AIGoYa/Likelion-13th-AIGoYa-Frontend, pull requests merged in 2025-08, with the labels that each got.

#7 feat: 날씨 컴포넌트 틀 구현
  aigoya/src/App.js
  aigoya/src/component/mainWeather.jsx
  aigoya/src/css/mainWeather.module.css
  aigoya/src/page/mainPage.js
Labels: ⭐ high, 🎯 feat

#9 feat: 시간대별 매출 현황 컴포넌트 큰 틀 구현
  aigoya/src/component/mainChart.js
  aigoya/src/css/mainChart.module.css
  aigoya/src/css/mainPage.module.css
Labels: ⭐ high, 🎯 feat

#17 style: 인기 메뉴, 주간 비인기메뉴 컴포넌트 틀 디자인 수정
  aigoya/package-lock.json
  aigoya/package.json
  aigoya/src/component/mainPopularMenu.jsx
  aigoya/src/component/mainUnpopularMenu.jsx
  aigoya/src/css/mainPopularMenu.module.css
  aigoya/src/css/mainUnpopularMenu.module.css
  aigoya/src/page/mainPage.js
Labels: 🎨 design, ⭐ high

#23 refactor: 로그인 페이지 라우터 설정 및 파일 구조 변경
  aigoya/src/App.js
  aigoya/src/page/loginPage.jsx
Labels: ⭐ high, 🔨 refactor

#24 refactor: 메인 페이지 컴포넌트 배치
  aigoya/src/css/mainPage.module.css
  aigoya/src/page/mainPage.jsx
Labels: ⭐ high, 🔨 refactor

#34 feat: 헤더 1차 생성
  aigoya/package-lock.json
  aigoya/package.json
  aigoya/src/component/header.jsx
  aigoya/src/component/mainSales.jsx
  aigoya/src/css/header.module.css
  aigoya/src/css/mainSales.module.css
  aigoya/src/page/mainPage.jsx
Labels: ⭐ high, 🎯 feat

#41 style: 전역스타일 body 색상 변경
  aigoya/src/App.css
  aigoya/src/css/mainPage.module.css
Labels: 🎨 design, ⭐ high

#46 feat: 포스기 페이지 구현
  aigoya/src/App.js
  aigoya/src/css/mainPage.module.css
  aigoya/src/css/posMachinePage.module.css
  aigoya/src/page/mainPage.jsx
  aigoya/src/page/posMachinePage.jsx
Labels: ⭐ high, 🎯 feat, 🔨 refactor

#51 refactor: 로그인 상태 리다이렉트 설정
  aigoya/src/api/storeApi.js
  aigoya/src/css/loginPage.module.css
  aigoya/src/page/loginPage.jsx
  aigoya/src/page/mainPage.jsx
Labels: ⭐ high, 🔨 refactor

#55 chore: 배포 및 깃액션 테스트1
  .github/workflows/deploy.yml
  aigoya/Dockerfile
  aigoya/Dockerfile.dev
Labels: 🔥 urgent, 🔧 chore

#68 feat: 매출 컴포넌트 API연결
  aigoya/src/api/StoreApi.js
  aigoya/src/component/MainSales.jsx
  aigoya/src/css/MainSales.module.css
Labels: ⭐ high, 🎯 feat

#81 feat: 매출관리 페이지 생성
  aigoya/src/App.js
  aigoya/src/component/SideBar.jsx
  aigoya/src/css/MyPage.module.css
  aigoya/src/css/OrderList.module.css
  aigoya/src/page/OrderList.jsx
Labels: ⭐ high, 🎯 feat

#82 refactor: 일별 인기, 주별 비인기 메뉴 api 연결
  aigoya/src/api/StoreApi.js
  aigoya/src/component/MainPopularMenu.jsx
  aigoya/src/component/MainUnpopularMenu.jsx
Labels: ⭐ high, 🔨 refactor

#84 refactor: 회원가입 주석 처리
  aigoya/src/api/StoreApi.js
  aigoya/src/page/SignUpPage.jsx
Labels: ⭐ high, 🔨 refactor

#87 feat: 직원 관리 페이지 생성
  aigoya/src/App.js
  aigoya/src/api/StoreApi.js
  aigoya/src/component/SideBar.jsx
  aigoya/src/css/EmployeePage.module.css
  aigoya/src/page/EmployeePage.jsx
Labels: ⭐ high, 🎯 feat

#89 design: 주문완료 후 모달 수량 위치 정렬
  aigoya/src/css/PosMachinePage.module.css
  aigoya/src/page/PosMachinePage.jsx
Labels: 🎨 design, 💤 low

#92 refactor: 챗봇 api 수정
  aigoya/src/api/StoreApi.js
  aigoya/src/page/ChatBotPage.jsx
Labels: ⭐ high, 🔨 refactor

#97 refactor: 파일 전체 불필요한 주석 제거
  aigoya/src/api/StoreApi.js
  aigoya/src/component/MainChart.jsx
  aigoya/src/component/MainPopularMenu.jsx
  aigoya/src/component/MainSales.jsx
  aigoya/src/component/MainUnpopularMenu.jsx
  aigoya/src/component/MainWeather.jsx
  aigoya/src/css/Header.module.css
  aigoya/src/page/ChatBotPage.jsx
  aigoya/src/page/EmployeePage.jsx
  aigoya/src/page/LoginPage.jsx
  aigoya/src/page/OrderList.jsx
  aigoya/src/page/PosMachinePage.jsx
Labels: ⭐ high, 🔨 refactor
